# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Anasayfa1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1501, 1049)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 20, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1180, 20, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 40, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 121, 20))
        self.label_4.setObjectName("label_4")
        self.Ad_Soyad = QtWidgets.QLineEdit(self.centralwidget)
        self.Ad_Soyad.setGeometry(QtCore.QRect(130, 85, 331, 22))
        self.Ad_Soyad.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"\n"
"}\n"
"")
        self.Ad_Soyad.setText("")
        self.Ad_Soyad.setObjectName("Ad_Soyad")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 81, 16))
        self.label_5.setObjectName("label_5")
        self.Adres = QtWidgets.QLineEdit(self.centralwidget)
        self.Adres.setGeometry(QtCore.QRect(130, 125, 331, 121))
        self.Adres.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:16px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Adres.setObjectName("Adres")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 270, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 300, 111, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 330, 171, 16))
        self.label_8.setObjectName("label_8")
        self.Telefon_Numarasi = QtWidgets.QLineEdit(self.centralwidget)
        self.Telefon_Numarasi.setGeometry(QtCore.QRect(200, 330, 231, 22))
        self.Telefon_Numarasi.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Telefon_Numarasi.setMaxLength(11)
        self.Telefon_Numarasi.setObjectName("Telefon_Numarasi")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 360, 111, 16))
        self.label_9.setObjectName("label_9")
        self.E_Posta = QtWidgets.QLineEdit(self.centralwidget)
        self.E_Posta.setGeometry(QtCore.QRect(190, 360, 231, 22))
        self.E_Posta.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.E_Posta.setObjectName("E_Posta")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(570, 255, 111, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(570, 85, 121, 20))
        self.label_11.setObjectName("label_11")
        self.Hasta_Ismi = QtWidgets.QLineEdit(self.centralwidget)
        self.Hasta_Ismi.setGeometry(QtCore.QRect(690, 85, 201, 22))
        self.Hasta_Ismi.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Hasta_Ismi.setText("")
        self.Hasta_Ismi.setObjectName("Hasta_Ismi")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(570, 285, 161, 16))
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(570, 45, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(570, 115, 131, 16))
        self.label_16.setObjectName("label_16")
        self.dogum_tarihi = QtWidgets.QDateEdit(self.centralwidget)
        self.dogum_tarihi.setGeometry(QtCore.QRect(710, 115, 110, 22))
        self.dogum_tarihi.setStyleSheet("QDateEdit{\n"
"border-radius:2px;\n"
"background-color: rgb(239, 231, 204);\n"
"border:2px solid rgb(221, 221, 221);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QDateEdit:hover{\n"
"border: 2px solid rgb(79, 83, 102);\n"
"}")
        self.dogum_tarihi.setCalendarPopup(True)
        self.dogum_tarihi.setObjectName("dogum_tarihi")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(570, 155, 111, 16))
        self.label_17.setObjectName("label_17")
        self.cmb_Cinsiyet = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_Cinsiyet.setGeometry(QtCore.QRect(660, 145, 141, 31))
        self.cmb_Cinsiyet.setStyleSheet("QComboBox{\n"
"border-radius:6px;\n"
"background-color: rgb(239, 231, 204);\n"
"border:2px solid rgb(221, 221, 221);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox:hover{\n"
"border: 2px solid rgb(79, 83, 102);\n"
"}")
        self.cmb_Cinsiyet.setObjectName("cmb_Cinsiyet")
        self.cmb_Cinsiyet.addItem("")
        self.cmb_Cinsiyet.addItem("")
        self.cmb_Cinsiyet.addItem("")
        self.cmb_Cinsiyet.addItem("")
        self.cmb_Cinsiyet.addItem("")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(570, 195, 111, 16))
        self.label_18.setObjectName("label_18")
        self.cmb_Cins = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_Cins.setGeometry(QtCore.QRect(660, 185, 141, 31))
        self.cmb_Cins.setStyleSheet("QComboBox{\n"
"border-radius:6px;\n"
"background-color: rgb(239, 231, 204);\n"
"border:2px solid rgb(221, 221, 221);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox:hover{\n"
"border: 2px solid rgb(79, 83, 102);\n"
"}")
        self.cmb_Cins.setObjectName("cmb_Cins")
        self.cmb_Cins.addItem("")
        self.cmb_Cins.addItem("")
        self.cmb_Cins.addItem("")
        self.cmb_Cins.addItem("")
        self.cmb_Cins.addItem("")
        self.cmb_Cins.addItem("")
        self.cmb_Cins.addItem("")
        self.cmb_Cins.addItem("")
        self.cmb_Cins.addItem("")
        self.Yavru = QtWidgets.QLineEdit(self.centralwidget)
        self.Yavru.setGeometry(QtCore.QRect(660, 225, 231, 22))
        self.Yavru.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Yavru.setText("")
        self.Yavru.setObjectName("Yavru")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(570, 225, 111, 16))
        self.label_19.setObjectName("label_19")
        self.dsb_Agirlik = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsb_Agirlik.setGeometry(QtCore.QRect(660, 255, 111, 22))
        self.dsb_Agirlik.setStyleSheet("border-radius:2px;\n"
"background-color: rgb(239, 231, 204);\n"
"border:2px solid rgb(221, 221, 221);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.dsb_Agirlik.setObjectName("dsb_Agirlik")
        self.chk_Yillik_Kontrol = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Yillik_Kontrol.setGeometry(QtCore.QRect(570, 305, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.chk_Yillik_Kontrol.setFont(font)
        self.chk_Yillik_Kontrol.setStyleSheet("")
        self.chk_Yillik_Kontrol.setObjectName("chk_Yillik_Kontrol")
        self.chk_Yavru_Kedi = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Yavru_Kedi.setGeometry(QtCore.QRect(570, 325, 111, 20))
        self.chk_Yavru_Kedi.setObjectName("chk_Yavru_Kedi")
        self.chk_Uyusukluk = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Uyusukluk.setGeometry(QtCore.QRect(570, 345, 101, 20))
        self.chk_Uyusukluk.setObjectName("chk_Uyusukluk")
        self.chk_Kusma = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Kusma.setGeometry(QtCore.QRect(570, 365, 81, 20))
        self.chk_Kusma.setObjectName("chk_Kusma")
        self.chk_Ishal = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Ishal.setGeometry(QtCore.QRect(690, 305, 81, 20))
        self.chk_Ishal.setObjectName("chk_Ishal")
        self.chk_Hapsirik = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Hapsirik.setGeometry(QtCore.QRect(690, 345, 91, 20))
        self.chk_Hapsirik.setObjectName("chk_Hapsirik")
        self.chk_Oksuruk = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Oksuruk.setGeometry(QtCore.QRect(690, 325, 81, 20))
        self.chk_Oksuruk.setObjectName("chk_Oksuruk")
        self.chk_Goz_Kontrol = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Goz_Kontrol.setGeometry(QtCore.QRect(690, 365, 111, 20))
        self.chk_Goz_Kontrol.setObjectName("chk_Goz_Kontrol")
        self.chk_Idrar_Yapma = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Idrar_Yapma.setGeometry(QtCore.QRect(940, 385, 211, 20))
        self.chk_Idrar_Yapma.setObjectName("chk_Idrar_Yapma")
        self.chk_Azalan_Istah = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Azalan_Istah.setGeometry(QtCore.QRect(940, 345, 121, 20))
        self.chk_Azalan_Istah.setObjectName("chk_Azalan_Istah")
        self.chk_Kulak_Kontrol = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Kulak_Kontrol.setGeometry(QtCore.QRect(800, 305, 121, 20))
        self.chk_Kulak_Kontrol.setObjectName("chk_Kulak_Kontrol")
        self.chk_Felc = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Felc.setGeometry(QtCore.QRect(940, 305, 81, 20))
        self.chk_Felc.setObjectName("chk_Felc")
        self.chk_Topallik = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Topallik.setGeometry(QtCore.QRect(800, 345, 81, 20))
        self.chk_Topallik.setObjectName("chk_Topallik")
        self.chk_Cilt_Kontrol = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Cilt_Kontrol.setGeometry(QtCore.QRect(800, 325, 111, 20))
        self.chk_Cilt_Kontrol.setObjectName("chk_Cilt_Kontrol")
        self.chk_Nefes_Problemi = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Nefes_Problemi.setGeometry(QtCore.QRect(800, 365, 141, 20))
        self.chk_Nefes_Problemi.setObjectName("chk_Nefes_Problemi")
        self.chk_Artan_Istah = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Artan_Istah.setGeometry(QtCore.QRect(940, 325, 111, 20))
        self.chk_Artan_Istah.setObjectName("chk_Artan_Istah")
        self.chkDis = QtWidgets.QCheckBox(self.centralwidget)
        self.chkDis.setGeometry(QtCore.QRect(570, 385, 71, 20))
        self.chkDis.setObjectName("chkDis")
        self.chk_Secmeli_Cerrahi = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Secmeli_Cerrahi.setGeometry(QtCore.QRect(940, 365, 211, 20))
        self.chk_Secmeli_Cerrahi.setObjectName("chk_Secmeli_Cerrahi")
        self.chk_Cerrahi = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Cerrahi.setGeometry(QtCore.QRect(690, 385, 101, 20))
        self.chk_Cerrahi.setObjectName("chk_Cerrahi")
        self.chk_Diger2 = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Diger2.setGeometry(QtCore.QRect(800, 385, 61, 20))
        self.chk_Diger2.setObjectName("chk_Diger2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 430, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 460, 101, 16))
        self.label_15.setObjectName("label_15")
        self.Sicaklik = QtWidgets.QLineEdit(self.centralwidget)
        self.Sicaklik.setGeometry(QtCore.QRect(130, 550, 231, 22))
        self.Sicaklik.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Sicaklik.setMaxLength(11)
        self.Sicaklik.setObjectName("Sicaklik")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 550, 91, 16))
        self.label_22.setObjectName("label_22")
        self.chk_Hareket = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Hareket.setGeometry(QtCore.QRect(130, 460, 91, 20))
        self.chk_Hareket.setObjectName("chk_Hareket")
        self.chk_Terli = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Terli.setGeometry(QtCore.QRect(130, 480, 81, 20))
        self.chk_Terli.setObjectName("chk_Terli")
        self.chk_Duyarsiz = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Duyarsiz.setGeometry(QtCore.QRect(130, 500, 91, 20))
        self.chk_Duyarsiz.setObjectName("chk_Duyarsiz")
        self.chk_Stresli = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Stresli.setGeometry(QtCore.QRect(250, 460, 81, 20))
        self.chk_Stresli.setObjectName("chk_Stresli")
        self.chk_Istikrarli = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Istikrarli.setGeometry(QtCore.QRect(250, 500, 91, 20))
        self.chk_Istikrarli.setObjectName("chk_Istikrarli")
        self.chk_Kuru = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Kuru.setGeometry(QtCore.QRect(250, 480, 81, 20))
        self.chk_Kuru.setObjectName("chk_Kuru")
        self.chk_Dinc = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Dinc.setGeometry(QtCore.QRect(370, 460, 81, 20))
        self.chk_Dinc.setObjectName("chk_Dinc")
        self.chk_Sokta = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Sokta.setGeometry(QtCore.QRect(370, 480, 81, 20))
        self.chk_Sokta.setObjectName("chk_Sokta")
        self.chk_Olasi = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Olasi.setGeometry(QtCore.QRect(370, 500, 141, 20))
        self.chk_Olasi.setObjectName("chk_Olasi")
        self.chk_Istikrarsiz = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Istikrarsiz.setGeometry(QtCore.QRect(130, 520, 101, 20))
        self.chk_Istikrarsiz.setObjectName("chk_Istikrarsiz")
        self.chk_Diger1 = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Diger1.setGeometry(QtCore.QRect(250, 520, 81, 20))
        self.chk_Diger1.setObjectName("chk_Diger1")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(20, 580, 101, 16))
        self.label_23.setObjectName("label_23")
        self.Kalp_Atisi = QtWidgets.QLineEdit(self.centralwidget)
        self.Kalp_Atisi.setGeometry(QtCore.QRect(130, 580, 231, 22))
        self.Kalp_Atisi.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Kalp_Atisi.setMaxLength(11)
        self.Kalp_Atisi.setObjectName("Kalp_Atisi")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(20, 610, 101, 16))
        self.label_24.setObjectName("label_24")
        self.Solunum = QtWidgets.QLineEdit(self.centralwidget)
        self.Solunum.setGeometry(QtCore.QRect(130, 610, 231, 22))
        self.Solunum.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Solunum.setMaxLength(11)
        self.Solunum.setObjectName("Solunum")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(20, 640, 161, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(20, 660, 101, 16))
        self.label_26.setObjectName("label_26")
        self.cmb_Puan = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_Puan.setGeometry(QtCore.QRect(190, 640, 211, 31))
        self.cmb_Puan.setStyleSheet("QComboBox{\n"
"border-radius:6px;\n"
"background-color: rgb(239, 231, 204);\n"
"border:2px solid rgb(221, 221, 221);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox:hover{\n"
"border: 2px solid rgb(79, 83, 102);\n"
"}")
        self.cmb_Puan.setObjectName("cmb_Puan")
        self.cmb_Puan.addItem("")
        self.cmb_Puan.addItem("")
        self.cmb_Puan.addItem("")
        self.cmb_Puan.addItem("")
        self.cmb_Puan.addItem("")
        self.cmb_Puan.addItem("")
        self.cmb_Puan.addItem("")
        self.cmb_Puan.addItem("")
        self.cmb_Puan.addItem("")
        self.cmb_Puan.addItem("")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(540, 460, 121, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(540, 480, 131, 21))
        self.label_28.setObjectName("label_28")
        self.Bulgu_Agiz_Boslugu = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu_Agiz_Boslugu.setGeometry(QtCore.QRect(680, 480, 231, 22))
        self.Bulgu_Agiz_Boslugu.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu_Agiz_Boslugu.setObjectName("Bulgu_Agiz_Boslugu")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(540, 530, 131, 21))
        self.label_29.setObjectName("label_29")
        self.Bulgu_Gozler = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu_Gozler.setGeometry(QtCore.QRect(680, 530, 231, 22))
        self.Bulgu_Gozler.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu_Gozler.setObjectName("Bulgu_Gozler")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(540, 510, 121, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(540, 590, 131, 21))
        self.label_31.setObjectName("label_31")
        self.Bulgu__Kulaklar = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu__Kulaklar.setGeometry(QtCore.QRect(680, 590, 231, 22))
        self.Bulgu__Kulaklar.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu__Kulaklar.setObjectName("Bulgu__Kulaklar")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(540, 570, 121, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(540, 650, 131, 21))
        self.label_33.setObjectName("label_33")
        self.Bulgu_Burun_Bogaz = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu_Burun_Bogaz.setGeometry(QtCore.QRect(680, 650, 231, 22))
        self.Bulgu_Burun_Bogaz.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu_Burun_Bogaz.setObjectName("Bulgu_Burun_Bogaz")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(540, 630, 121, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(540, 710, 131, 21))
        self.label_35.setObjectName("label_35")
        self.Bulgu_Kalp = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu_Kalp.setGeometry(QtCore.QRect(680, 710, 231, 22))
        self.Bulgu_Kalp.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu_Kalp.setObjectName("Bulgu_Kalp")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(540, 690, 121, 16))
        self.label_36.setObjectName("label_36")
        self.Bulgu_Iskelet_Kas = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu_Iskelet_Kas.setGeometry(QtCore.QRect(1080, 710, 231, 22))
        self.Bulgu_Iskelet_Kas.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu_Iskelet_Kas.setObjectName("Bulgu_Iskelet_Kas")
        self.Bulgu_Akcigerler = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu_Akcigerler.setGeometry(QtCore.QRect(1080, 480, 231, 22))
        self.Bulgu_Akcigerler.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu_Akcigerler.setObjectName("Bulgu_Akcigerler")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(940, 630, 121, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(940, 710, 131, 21))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(940, 480, 131, 21))
        self.label_39.setObjectName("label_39")
        self.Bulgu_Karin = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu_Karin.setGeometry(QtCore.QRect(1080, 530, 231, 22))
        self.Bulgu_Karin.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu_Karin.setObjectName("Bulgu_Karin")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(940, 590, 131, 21))
        self.label_40.setObjectName("label_40")
        self.Bulgu_Lenf_Dugumleri = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu_Lenf_Dugumleri.setGeometry(QtCore.QRect(1080, 590, 231, 22))
        self.Bulgu_Lenf_Dugumleri.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu_Lenf_Dugumleri.setObjectName("Bulgu_Lenf_Dugumleri")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(940, 570, 151, 16))
        self.label_41.setObjectName("label_41")
        self.Bulgu_Deri = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu_Deri.setGeometry(QtCore.QRect(1080, 650, 231, 22))
        self.Bulgu_Deri.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu_Deri.setObjectName("Bulgu_Deri")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(940, 530, 131, 21))
        self.label_42.setObjectName("label_42")
        self.B = QtWidgets.QLabel(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(940, 690, 121, 16))
        self.B.setObjectName("B")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(940, 460, 121, 16))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(940, 510, 121, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(940, 650, 131, 21))
        self.label_46.setObjectName("label_46")
        self.Bulgu_Sinirler = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu_Sinirler.setGeometry(QtCore.QRect(680, 760, 231, 22))
        self.Bulgu_Sinirler.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu_Sinirler.setObjectName("Bulgu_Sinirler")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(540, 760, 131, 21))
        self.label_49.setObjectName("label_49")
        self.Bulgu_Urogenital = QtWidgets.QLineEdit(self.centralwidget)
        self.Bulgu_Urogenital.setGeometry(QtCore.QRect(1080, 760, 231, 22))
        self.Bulgu_Urogenital.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(221, 221, 221);\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(79, 83, 102);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.Bulgu_Urogenital.setObjectName("Bulgu_Urogenital")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(940, 760, 131, 21))
        self.label_52.setObjectName("label_52")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(540, 740, 121, 16))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(940, 740, 121, 16))
        self.label_55.setObjectName("label_55")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(30, 790, 161, 16))
        self.label_47.setObjectName("label_47")
        self.chk_Idrar_Tahlili = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Idrar_Tahlili.setGeometry(QtCore.QRect(290, 850, 121, 20))
        self.chk_Idrar_Tahlili.setObjectName("chk_Idrar_Tahlili")
        self.chk_Laym_Titre = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Laym_Titre.setGeometry(QtCore.QRect(290, 810, 121, 20))
        self.chk_Laym_Titre.setObjectName("chk_Laym_Titre")
        self.chk_Karin_Ultrasonu = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Karin_Ultrasonu.setGeometry(QtCore.QRect(130, 870, 141, 20))
        self.chk_Karin_Ultrasonu.setObjectName("chk_Karin_Ultrasonu")
        self.chk_Idrar_Gosterimi = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Idrar_Gosterimi.setGeometry(QtCore.QRect(290, 890, 211, 20))
        self.chk_Idrar_Gosterimi.setObjectName("chk_Idrar_Gosterimi")
        self.chk_Radyografi = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Radyografi.setGeometry(QtCore.QRect(130, 850, 111, 20))
        self.chk_Radyografi.setObjectName("chk_Radyografi")
        self.chk_C_S = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_C_S.setGeometry(QtCore.QRect(130, 890, 141, 20))
        self.chk_C_S.setObjectName("chk_C_S")
        self.chk_CBC = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_CBC.setGeometry(QtCore.QRect(30, 810, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.chk_CBC.setFont(font)
        self.chk_CBC.setStyleSheet("")
        self.chk_CBC.setObjectName("chk_CBC")
        self.chk_Ameliyat_Oncesi_Kan_Tahlili = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Ameliyat_Oncesi_Kan_Tahlili.setGeometry(QtCore.QRect(290, 830, 221, 20))
        self.chk_Ameliyat_Oncesi_Kan_Tahlili.setObjectName("chk_Ameliyat_Oncesi_Kan_Tahlili")
        self.chk_Biyopsi = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Biyopsi.setGeometry(QtCore.QRect(130, 810, 81, 20))
        self.chk_Biyopsi.setObjectName("chk_Biyopsi")
        self.chk_ECG = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_ECG.setGeometry(QtCore.QRect(30, 850, 91, 20))
        self.chk_ECG.setObjectName("chk_ECG")
        self.chk_T4 = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_T4.setGeometry(QtCore.QRect(30, 830, 91, 20))
        self.chk_T4.setObjectName("chk_T4")
        self.chk_Yankl_Yurek_Gosterimi = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Yankl_Yurek_Gosterimi.setGeometry(QtCore.QRect(290, 870, 201, 20))
        self.chk_Yankl_Yurek_Gosterimi.setObjectName("chk_Yankl_Yurek_Gosterimi")
        self.chk_Felv_Fiv = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Felv_Fiv.setGeometry(QtCore.QRect(30, 890, 101, 20))
        self.chk_Felv_Fiv.setObjectName("chk_Felv_Fiv")
        self.chk_Deri_Testi = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Deri_Testi.setGeometry(QtCore.QRect(30, 870, 101, 20))
        self.chk_Deri_Testi.setObjectName("chk_Deri_Testi")
        self.chk_Chem = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Chem.setGeometry(QtCore.QRect(130, 830, 81, 20))
        self.chk_Chem.setObjectName("chk_Chem")
        self.chk_Kalp_Kurdu_Testi = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Kalp_Kurdu_Testi.setGeometry(QtCore.QRect(130, 910, 201, 20))
        self.chk_Kalp_Kurdu_Testi.setObjectName("chk_Kalp_Kurdu_Testi")
        self.chk_Diski = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Diski.setGeometry(QtCore.QRect(30, 910, 91, 20))
        self.chk_Diski.setObjectName("chk_Diski")
        self.chk_Diger3 = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_Diger3.setGeometry(QtCore.QRect(290, 910, 211, 20))
        self.chk_Diger3.setObjectName("chk_Diger3")
        self.de_Tarih = QtWidgets.QDateEdit(self.centralwidget)
        self.de_Tarih.setGeometry(QtCore.QRect(1240, 20, 110, 22))
        self.de_Tarih.setStyleSheet("QDateEdit{\n"
"border-radius:2px;\n"
"background-color: rgb(239, 231, 204);\n"
"border:2px solid rgb(221, 221, 221);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QDateEdit:hover{\n"
"border: 2px solid rgb(79, 83, 102);\n"
"}")
        self.de_Tarih.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 6, 9), QtCore.QTime(0, 0, 0)))
        self.de_Tarih.setMinimumDate(QtCore.QDate(2022, 1, 1))
        self.de_Tarih.setCalendarPopup(True)
        self.de_Tarih.setObjectName("de_Tarih")
        self.btn_ileri = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ileri.setGeometry(QtCore.QRect(1280, 900, 93, 41))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.btn_ileri.setFont(font)
        self.btn_ileri.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.btn_ileri.setObjectName("btn_ileri")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 1441, 971))
        self.label_20.setStyleSheet("background-color: rgb(193, 187, 168);\n"
"border-radius: 50px;")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.Il = QtWidgets.QComboBox(self.centralwidget)
        self.Il.setGeometry(QtCore.QRect(130, 260, 231, 22))
        self.Il.setStyleSheet("QComboBox{\n"
"border-radius:6px;\n"
"background-color: rgb(239, 231, 204);\n"
"border:2px solid rgb(221, 221, 221);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox:hover{\n"
"border: 2px solid rgb(79, 83, 102);\n"
"}")
        self.Il.setObjectName("Il")
        self.rb_normal1 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal1.setGeometry(QtCore.QRect(690, 460, 81, 20))
        self.rb_normal1.setObjectName("rb_normal1")
        self.rb_anormal1 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal1.setGeometry(QtCore.QRect(810, 460, 81, 20))
        self.rb_anormal1.setObjectName("rb_anormal1")
        self.rb_normal2 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal2.setGeometry(QtCore.QRect(690, 510, 81, 20))
        self.rb_normal2.setObjectName("rb_normal2")
        self.rb_normal3 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal3.setGeometry(QtCore.QRect(690, 570, 81, 20))
        self.rb_normal3.setObjectName("rb_normal3")
        self.rb_normal4 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal4.setGeometry(QtCore.QRect(690, 630, 81, 20))
        self.rb_normal4.setObjectName("rb_normal4")
        self.rb_normal5 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal5.setGeometry(QtCore.QRect(690, 690, 81, 20))
        self.rb_normal5.setObjectName("rb_normal5")
        self.rb_normal6 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal6.setGeometry(QtCore.QRect(690, 740, 81, 20))
        self.rb_normal6.setObjectName("rb_normal6")
        self.rb_anormal2 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal2.setGeometry(QtCore.QRect(810, 510, 81, 20))
        self.rb_anormal2.setObjectName("rb_anormal2")
        self.rb_anormal3 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal3.setGeometry(QtCore.QRect(810, 570, 81, 20))
        self.rb_anormal3.setObjectName("rb_anormal3")
        self.rb_anormal4 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal4.setGeometry(QtCore.QRect(810, 630, 81, 20))
        self.rb_anormal4.setObjectName("rb_anormal4")
        self.rb_anormal5 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal5.setGeometry(QtCore.QRect(810, 690, 81, 20))
        self.rb_anormal5.setObjectName("rb_anormal5")
        self.rb_anormal6 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal6.setGeometry(QtCore.QRect(810, 740, 81, 20))
        self.rb_anormal6.setObjectName("rb_anormal6")
        self.rb_anormal7 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal7.setGeometry(QtCore.QRect(1220, 460, 81, 20))
        self.rb_anormal7.setObjectName("rb_anormal7")
        self.rb_anormal8 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal8.setGeometry(QtCore.QRect(1220, 510, 81, 20))
        self.rb_anormal8.setObjectName("rb_anormal8")
        self.rb_anormal9 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal9.setGeometry(QtCore.QRect(1220, 570, 81, 20))
        self.rb_anormal9.setObjectName("rb_anormal9")
        self.rb_anormal10 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal10.setGeometry(QtCore.QRect(1220, 630, 81, 20))
        self.rb_anormal10.setObjectName("rb_anormal10")
        self.rb_anormal11 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal11.setGeometry(QtCore.QRect(1220, 690, 81, 20))
        self.rb_anormal11.setObjectName("rb_anormal11")
        self.rb_anormal12 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_anormal12.setGeometry(QtCore.QRect(1220, 740, 81, 20))
        self.rb_anormal12.setObjectName("rb_anormal12")
        self.rb_normal7 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal7.setGeometry(QtCore.QRect(1090, 460, 81, 20))
        self.rb_normal7.setObjectName("rb_normal7")
        self.rb_normal8 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal8.setGeometry(QtCore.QRect(1090, 510, 81, 20))
        self.rb_normal8.setObjectName("rb_normal8")
        self.rb_normal9 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal9.setGeometry(QtCore.QRect(1090, 570, 81, 20))
        self.rb_normal9.setObjectName("rb_normal9")
        self.rb_normal10 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal10.setGeometry(QtCore.QRect(1090, 630, 81, 20))
        self.rb_normal10.setObjectName("rb_normal10")
        self.rb_normal11 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal11.setGeometry(QtCore.QRect(1090, 690, 81, 20))
        self.rb_normal11.setObjectName("rb_normal11")
        self.rb_normal12 = QtWidgets.QCheckBox(self.centralwidget)
        self.rb_normal12.setGeometry(QtCore.QRect(1090, 740, 81, 20))
        self.rb_normal12.setObjectName("rb_normal12")
        self.Ilce = QtWidgets.QComboBox(self.centralwidget)
        self.Ilce.setGeometry(QtCore.QRect(130, 290, 231, 22))
        self.Ilce.setStyleSheet("QComboBox{\n"
"border-radius:6px;\n"
"background-color: rgb(239, 231, 204);\n"
"border:2px solid rgb(221, 221, 221);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox:hover{\n"
"border: 2px solid rgb(79, 83, 102);\n"
"}")
        self.Ilce.setObjectName("Ilce")
        self.label_20.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.Ad_Soyad.raise_()
        self.label_5.raise_()
        self.Adres.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.Telefon_Numarasi.raise_()
        self.label_9.raise_()
        self.E_Posta.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.Hasta_Ismi.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.label_16.raise_()
        self.dogum_tarihi.raise_()
        self.label_17.raise_()
        self.cmb_Cinsiyet.raise_()
        self.label_18.raise_()
        self.cmb_Cins.raise_()
        self.Yavru.raise_()
        self.label_19.raise_()
        self.dsb_Agirlik.raise_()
        self.chk_Yillik_Kontrol.raise_()
        self.chk_Yavru_Kedi.raise_()
        self.chk_Uyusukluk.raise_()
        self.chk_Kusma.raise_()
        self.chk_Ishal.raise_()
        self.chk_Hapsirik.raise_()
        self.chk_Oksuruk.raise_()
        self.chk_Goz_Kontrol.raise_()
        self.chk_Idrar_Yapma.raise_()
        self.chk_Azalan_Istah.raise_()
        self.chk_Kulak_Kontrol.raise_()
        self.chk_Felc.raise_()
        self.chk_Topallik.raise_()
        self.chk_Cilt_Kontrol.raise_()
        self.chk_Nefes_Problemi.raise_()
        self.chk_Artan_Istah.raise_()
        self.chkDis.raise_()
        self.chk_Secmeli_Cerrahi.raise_()
        self.chk_Cerrahi.raise_()
        self.chk_Diger2.raise_()
        self.label_13.raise_()
        self.label_15.raise_()
        self.Sicaklik.raise_()
        self.label_22.raise_()
        self.chk_Hareket.raise_()
        self.chk_Terli.raise_()
        self.chk_Duyarsiz.raise_()
        self.chk_Stresli.raise_()
        self.chk_Istikrarli.raise_()
        self.chk_Kuru.raise_()
        self.chk_Dinc.raise_()
        self.chk_Sokta.raise_()
        self.chk_Olasi.raise_()
        self.chk_Istikrarsiz.raise_()
        self.chk_Diger1.raise_()
        self.label_23.raise_()
        self.Kalp_Atisi.raise_()
        self.label_24.raise_()
        self.Solunum.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.cmb_Puan.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.Bulgu_Agiz_Boslugu.raise_()
        self.label_29.raise_()
        self.Bulgu_Gozler.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.Bulgu__Kulaklar.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.Bulgu_Burun_Bogaz.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.Bulgu_Kalp.raise_()
        self.label_36.raise_()
        self.Bulgu_Iskelet_Kas.raise_()
        self.Bulgu_Akcigerler.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.Bulgu_Karin.raise_()
        self.label_40.raise_()
        self.Bulgu_Lenf_Dugumleri.raise_()
        self.label_41.raise_()
        self.Bulgu_Deri.raise_()
        self.label_42.raise_()
        self.B.raise_()
        self.label_44.raise_()
        self.label_45.raise_()
        self.label_46.raise_()
        self.Bulgu_Sinirler.raise_()
        self.label_49.raise_()
        self.Bulgu_Urogenital.raise_()
        self.label_52.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_47.raise_()
        self.chk_Idrar_Tahlili.raise_()
        self.chk_Laym_Titre.raise_()
        self.chk_Karin_Ultrasonu.raise_()
        self.chk_Idrar_Gosterimi.raise_()
        self.chk_Radyografi.raise_()
        self.chk_C_S.raise_()
        self.chk_CBC.raise_()
        self.chk_Ameliyat_Oncesi_Kan_Tahlili.raise_()
        self.chk_Biyopsi.raise_()
        self.chk_ECG.raise_()
        self.chk_T4.raise_()
        self.chk_Yankl_Yurek_Gosterimi.raise_()
        self.chk_Felv_Fiv.raise_()
        self.chk_Deri_Testi.raise_()
        self.chk_Chem.raise_()
        self.chk_Kalp_Kurdu_Testi.raise_()
        self.chk_Diski.raise_()
        self.chk_Diger3.raise_()
        self.de_Tarih.raise_()
        self.btn_ileri.raise_()
        self.Il.raise_()
        self.rb_normal1.raise_()
        self.rb_anormal1.raise_()
        self.rb_normal2.raise_()
        self.rb_normal3.raise_()
        self.rb_normal4.raise_()
        self.rb_normal5.raise_()
        self.rb_normal6.raise_()
        self.rb_anormal2.raise_()
        self.rb_anormal3.raise_()
        self.rb_anormal4.raise_()
        self.rb_anormal5.raise_()
        self.rb_anormal6.raise_()
        self.rb_anormal7.raise_()
        self.rb_anormal8.raise_()
        self.rb_anormal9.raise_()
        self.rb_anormal10.raise_()
        self.rb_anormal11.raise_()
        self.rb_anormal12.raise_()
        self.rb_normal7.raise_()
        self.rb_normal8.raise_()
        self.rb_normal9.raise_()
        self.rb_normal10.raise_()
        self.rb_normal11.raise_()
        self.rb_normal12.raise_()
        self.Ilce.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1501, 26))
        self.menubar.setObjectName("menubar")
        self.menuYard_m = QtWidgets.QMenu(self.menubar)
        self.menuYard_m.setObjectName("menuYard_m")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuhakkinda = QtWidgets.QAction(MainWindow)
        self.menuhakkinda.setObjectName("menuhakkinda")
        self.menuYard_m.addAction(self.menuhakkinda)
        self.menubar.addAction(self.menuYard_m.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "VETERİNER TAKİP FORMU"))
        self.label_2.setText(_translate("MainWindow", "Tarih:"))
        self.label_3.setText(_translate("MainWindow", "Hayvan Sahibine Ait Bilgiler"))
        self.label_4.setText(_translate("MainWindow", "AD- SOYAD:"))
        self.label_5.setText(_translate("MainWindow", "ADRES:"))
        self.label_6.setText(_translate("MainWindow", "İL:"))
        self.label_7.setText(_translate("MainWindow", "İLÇE:"))
        self.label_8.setText(_translate("MainWindow", "TELEFON NUMARASI:"))
        self.label_9.setText(_translate("MainWindow", "E-POSTA:"))
        self.label_10.setText(_translate("MainWindow", "AĞIRLIK:"))
        self.label_11.setText(_translate("MainWindow", "HASTA İSMİ:"))
        self.label_12.setText(_translate("MainWindow", "TEMEL ŞİKAYETLER:"))
        self.label_14.setText(_translate("MainWindow", "HAYVAN BİLGİLERİ"))
        self.label_16.setText(_translate("MainWindow", "DOĞUM TARİHİ:"))
        self.label_17.setText(_translate("MainWindow", "CİNSİYET:"))
        self.cmb_Cinsiyet.setItemText(0, _translate("MainWindow", "Seçiniz"))
        self.cmb_Cinsiyet.setItemText(1, _translate("MainWindow", "Dişi"))
        self.cmb_Cinsiyet.setItemText(2, _translate("MainWindow", "Erkek"))
        self.cmb_Cinsiyet.setItemText(3, _translate("MainWindow", "Kısırlaştırılmış Dişi"))
        self.cmb_Cinsiyet.setItemText(4, _translate("MainWindow", "Kısırlaştırılmış Erkek"))
        self.label_18.setText(_translate("MainWindow", "CİNS:"))
        self.cmb_Cins.setItemText(0, _translate("MainWindow", "Seçiniz"))
        self.cmb_Cins.setItemText(1, _translate("MainWindow", "Kedi"))
        self.cmb_Cins.setItemText(2, _translate("MainWindow", "Köpek"))
        self.cmb_Cins.setItemText(3, _translate("MainWindow", "At"))
        self.cmb_Cins.setItemText(4, _translate("MainWindow", "Büyükbaş"))
        self.cmb_Cins.setItemText(5, _translate("MainWindow", "Küçükbaş"))
        self.cmb_Cins.setItemText(6, _translate("MainWindow", "Kuş"))
        self.cmb_Cins.setItemText(7, _translate("MainWindow", "Sürüngen"))
        self.cmb_Cins.setItemText(8, _translate("MainWindow", "Diğer"))
        self.label_19.setText(_translate("MainWindow", "YAVRU:"))
        self.chk_Yillik_Kontrol.setText(_translate("MainWindow", "Yıllık Kontrol"))
        self.chk_Yavru_Kedi.setText(_translate("MainWindow", "Yavru Kedi"))
        self.chk_Uyusukluk.setText(_translate("MainWindow", "Uyuşukluk"))
        self.chk_Kusma.setText(_translate("MainWindow", "Kusma"))
        self.chk_Ishal.setText(_translate("MainWindow", "İshal"))
        self.chk_Hapsirik.setText(_translate("MainWindow", "Hapşırma"))
        self.chk_Oksuruk.setText(_translate("MainWindow", "Öksürük"))
        self.chk_Goz_Kontrol.setText(_translate("MainWindow", "Göz Kontrol"))
        self.chk_Idrar_Yapma.setText(_translate("MainWindow", "Artan İçme/İdrar Yapma"))
        self.chk_Azalan_Istah.setText(_translate("MainWindow", "Azalan İştah"))
        self.chk_Kulak_Kontrol.setText(_translate("MainWindow", "Kulak Kontrol"))
        self.chk_Felc.setText(_translate("MainWindow", "Felç"))
        self.chk_Topallik.setText(_translate("MainWindow", "Topallık"))
        self.chk_Cilt_Kontrol.setText(_translate("MainWindow", "Cilt Kontrol"))
        self.chk_Nefes_Problemi.setText(_translate("MainWindow", "Nefes Problemi"))
        self.chk_Artan_Istah.setText(_translate("MainWindow", "Artan İştah"))
        self.chkDis.setText(_translate("MainWindow", "Diş"))
        self.chk_Secmeli_Cerrahi.setText(_translate("MainWindow", "Seçmeli Cerrahi"))
        self.chk_Cerrahi.setText(_translate("MainWindow", "Cerrahi"))
        self.chk_Diger2.setText(_translate("MainWindow", "Diğer"))
        self.label_13.setText(_translate("MainWindow", "FİZİKSEL TEST BULGULARI"))
        self.label_15.setText(_translate("MainWindow", "ÖN GÖZLEM:"))
        self.label_22.setText(_translate("MainWindow", "SICAKLIK:"))
        self.chk_Hareket.setText(_translate("MainWindow", "Hareketli"))
        self.chk_Terli.setText(_translate("MainWindow", "Terli"))
        self.chk_Duyarsiz.setText(_translate("MainWindow", "Duyarsız"))
        self.chk_Stresli.setText(_translate("MainWindow", "Stresli"))
        self.chk_Istikrarli.setText(_translate("MainWindow", "İstikrarlı"))
        self.chk_Kuru.setText(_translate("MainWindow", "Kuru"))
        self.chk_Dinc.setText(_translate("MainWindow", "Dinç"))
        self.chk_Sokta.setText(_translate("MainWindow", "Şokta"))
        self.chk_Olasi.setText(_translate("MainWindow", "Olası İstikrarsız"))
        self.chk_Istikrarsiz.setText(_translate("MainWindow", "İstikrarsız"))
        self.chk_Diger1.setText(_translate("MainWindow", "Diğer"))
        self.label_23.setText(_translate("MainWindow", "KALP ATIŞI:"))
        self.label_24.setText(_translate("MainWindow", "SOLUNUM:"))
        self.label_25.setText(_translate("MainWindow", "VÜCÜT KONDİSYON,"))
        self.label_26.setText(_translate("MainWindow", "PUANI:"))
        self.cmb_Puan.setItemText(0, _translate("MainWindow", "Seçiniz"))
        self.cmb_Puan.setItemText(1, _translate("MainWindow", "1/9"))
        self.cmb_Puan.setItemText(2, _translate("MainWindow", "2/9"))
        self.cmb_Puan.setItemText(3, _translate("MainWindow", "3/9"))
        self.cmb_Puan.setItemText(4, _translate("MainWindow", "4/9"))
        self.cmb_Puan.setItemText(5, _translate("MainWindow", "5/9"))
        self.cmb_Puan.setItemText(6, _translate("MainWindow", "6/9"))
        self.cmb_Puan.setItemText(7, _translate("MainWindow", "7/9"))
        self.cmb_Puan.setItemText(8, _translate("MainWindow", "8/9"))
        self.cmb_Puan.setItemText(9, _translate("MainWindow", "9/9"))
        self.label_27.setText(_translate("MainWindow", "AĞIZ BOŞLUĞU:"))
        self.label_28.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.label_29.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.label_30.setText(_translate("MainWindow", "GÖZLER:"))
        self.label_31.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.label_32.setText(_translate("MainWindow", "KULAKLAR:"))
        self.label_33.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.label_34.setText(_translate("MainWindow", "BURUN/BOĞAZ:"))
        self.label_35.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.label_36.setText(_translate("MainWindow", "KALP:"))
        self.label_37.setText(_translate("MainWindow", "DERİ:"))
        self.label_38.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.label_39.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.label_40.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.label_41.setText(_translate("MainWindow", "LENF DÜĞÜMLERİ:"))
        self.label_42.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.B.setText(_translate("MainWindow", "İSKELET/KAS:"))
        self.label_44.setText(_translate("MainWindow", "AKCİĞERLER:"))
        self.label_45.setText(_translate("MainWindow", "KARIN:"))
        self.label_46.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.label_49.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.label_52.setText(_translate("MainWindow", "Anormal Bulgular"))
        self.label_54.setText(_translate("MainWindow", "SİNİRLER:"))
        self.label_55.setText(_translate("MainWindow", "UROGENİTAL:"))
        self.label_47.setText(_translate("MainWindow", "TEŞHİSLER"))
        self.chk_Idrar_Tahlili.setText(_translate("MainWindow", "İdrar Tahlili"))
        self.chk_Laym_Titre.setText(_translate("MainWindow", "Laym Titre"))
        self.chk_Karin_Ultrasonu.setText(_translate("MainWindow", "Karın Ultrasonu"))
        self.chk_Idrar_Gosterimi.setText(_translate("MainWindow", "İdrar Gösterimi"))
        self.chk_Radyografi.setText(_translate("MainWindow", "Radyografi"))
        self.chk_C_S.setText(_translate("MainWindow", "Aerobic C ve S"))
        self.chk_CBC.setText(_translate("MainWindow", "CBC"))
        self.chk_Ameliyat_Oncesi_Kan_Tahlili.setText(_translate("MainWindow", "Ameliyat Öncesi Kan Tahlili"))
        self.chk_Biyopsi.setText(_translate("MainWindow", "Biyopsi"))
        self.chk_ECG.setText(_translate("MainWindow", "ECG"))
        self.chk_T4.setText(_translate("MainWindow", "T4"))
        self.chk_Yankl_Yurek_Gosterimi.setText(_translate("MainWindow", "Yankılı Yürek Gösterimi"))
        self.chk_Felv_Fiv.setText(_translate("MainWindow", "FELV/FIV"))
        self.chk_Deri_Testi.setText(_translate("MainWindow", "Deri Testi"))
        self.chk_Chem.setText(_translate("MainWindow", "Chem"))
        self.chk_Kalp_Kurdu_Testi.setText(_translate("MainWindow", "Kalp Kurdu Testi"))
        self.chk_Diski.setText(_translate("MainWindow", "Dışkı"))
        self.chk_Diger3.setText(_translate("MainWindow", "Diğer"))
        self.btn_ileri.setText(_translate("MainWindow", ""))
        self.rb_normal1.setText(_translate("MainWindow", "Normal"))
        self.rb_anormal1.setText(_translate("MainWindow", "Anormal"))
        self.rb_normal2.setText(_translate("MainWindow", "Normal"))
        self.rb_normal3.setText(_translate("MainWindow", "Normal"))
        self.rb_normal4.setText(_translate("MainWindow", "Normal"))
        self.rb_normal5.setText(_translate("MainWindow", "Normal"))
        self.rb_normal6.setText(_translate("MainWindow", "Normal"))
        self.rb_anormal2.setText(_translate("MainWindow", "Anormal"))
        self.rb_anormal3.setText(_translate("MainWindow", "Anormal"))
        self.rb_anormal4.setText(_translate("MainWindow", "Anormal"))
        self.rb_anormal5.setText(_translate("MainWindow", "Anormal"))
        self.rb_anormal6.setText(_translate("MainWindow", "Anormal"))
        self.rb_anormal7.setText(_translate("MainWindow", "Anormal"))
        self.rb_anormal8.setText(_translate("MainWindow", "Anormal"))
        self.rb_anormal9.setText(_translate("MainWindow", "Anormal"))
        self.rb_anormal10.setText(_translate("MainWindow", "Anormal"))
        self.rb_anormal11.setText(_translate("MainWindow", "Anormal"))
        self.rb_anormal12.setText(_translate("MainWindow", "Anormal"))
        self.rb_normal7.setText(_translate("MainWindow", "Normal"))
        self.rb_normal8.setText(_translate("MainWindow", "Normal"))
        self.rb_normal9.setText(_translate("MainWindow", "Normal"))
        self.rb_normal10.setText(_translate("MainWindow", "Normal"))
        self.rb_normal11.setText(_translate("MainWindow", "Normal"))
        self.rb_normal12.setText(_translate("MainWindow", "Normal"))
        self.menuYard_m.setTitle(_translate("MainWindow", "Yardım"))
        self.menuhakkinda.setText(_translate("MainWindow", "Hakkında"))
