# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GirisEkrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Giris(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 611)
        Dialog.setStyleSheet("background-color: rgb(239, 231, 204);\n"
"")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(40, 40, 391, 531))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        self.lineEdit.setFont(font)
        self.lineEdit.setMouseTracking(True)
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setStyleSheet("background-color: rgb(193, 187, 168);\n"
"border-radius: 40px;")
        self.lineEdit.setObjectName("lineEdit")
        self.btngirisyap = QtWidgets.QPushButton(Dialog)
        self.btngirisyap.setGeometry(QtCore.QRect(110, 390, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btngirisyap.setFont(font)
        self.btngirisyap.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(196, 199, 198);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    background-color: rgb(143, 145, 144);\n"
"}")
        self.btngirisyap.setObjectName("btngirisyap")
        self.rdsifregosterr = QtWidgets.QRadioButton(Dialog)
        self.rdsifregosterr.setGeometry(QtCore.QRect(110, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.rdsifregosterr.setFont(font)
        self.rdsifregosterr.setStyleSheet("background-color: rgb(193, 187, 168);\n"
"color: black;")
        self.rdsifregosterr.setObjectName("rdsifregosterr")
        self.btnkayitolmak = QtWidgets.QPushButton(Dialog)
        self.btnkayitolmak.setGeometry(QtCore.QRect(280, 350, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnkayitolmak.setFont(font)
        self.btnkayitolmak.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(196, 199, 198);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    background-color: rgb(143, 145, 144);\n"
"}")
        self.btnkayitolmak.setObjectName("btnkayitolmak")
        self.btncikisyap = QtWidgets.QPushButton(Dialog)
        self.btncikisyap.setGeometry(QtCore.QRect(230, 390, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btncikisyap.setFont(font)
        self.btncikisyap.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(196, 199, 198);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    background-color: rgb(143, 145, 144);\n"
"}")
        self.btncikisyap.setObjectName("btncikisyap")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 70, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(193, 187, 168);\n"
"\n"
"")
        self.label.setObjectName("label")
        self.lnekullaniciadi = QtWidgets.QLineEdit(Dialog)
        self.lnekullaniciadi.setGeometry(QtCore.QRect(100, 190, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.lnekullaniciadi.setFont(font)
        self.lnekullaniciadi.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(37, 39, 48);\n"
"    border-radius:20px;\n"
"    color: black;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    \n"
"    \n"
"    background-color: rgb(196, 199, 198);\n"
"    \n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    \n"
"    background-color: rgb(143, 145, 144);\n"
"}")
        self.lnekullaniciadi.setObjectName("lnekullaniciadi")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 350, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: black;\n"
"background-color: rgb(193, 187, 168);")
        self.label_2.setObjectName("label_2")
        self.lnesifre = QtWidgets.QLineEdit(Dialog)
        self.lnesifre.setGeometry(QtCore.QRect(100, 240, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.lnesifre.setFont(font)
        self.lnesifre.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(37, 39, 48);\n"
"    border-radius:20px;\n"
"    color: black;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    \n"
"    \n"
"    background-color: rgb(196, 199, 198);\n"
"    \n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    \n"
"    background-color: rgb(143, 145, 144);\n"
"}")
        self.lnesifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnesifre.setObjectName("lnesifre")
        self.btnytube = QtWidgets.QPushButton(Dialog)
        self.btnytube.setGeometry(QtCore.QRect(360, 460, 40, 40))
        self.btnytube.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(28)
        self.btnytube.setFont(font)
        self.btnytube.setStyleSheet("QPushButton{\n"
"    background:#636363;\n"
"    border-style: outset;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(196, 199, 198);\n"
"    border-style: inset;\n"
"}\n"
"")
        self.btnytube.setObjectName("btnytube")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 470, 291, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: black;\n"
"background-color: rgb(193, 187, 168);")
        self.label_3.setObjectName("label_3")
        self.lineEdit.raise_()
        self.btngirisyap.raise_()
        self.rdsifregosterr.raise_()
        self.btncikisyap.raise_()
        self.label.raise_()
        self.lnekullaniciadi.raise_()
        self.lnesifre.raise_()
        self.label_2.raise_()
        self.btnkayitolmak.raise_()
        self.btnytube.raise_()
        self.label_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Giriş"))
        self.btngirisyap.setText(_translate("Dialog", "Giriş Yap"))
        self.rdsifregosterr.setText(_translate("Dialog", "Şifreyi göster"))
        self.btnkayitolmak.setText(_translate("Dialog", "Kayıt Ol"))
        self.btncikisyap.setText(_translate("Dialog", "Çıkış"))
        self.label.setText(_translate("Dialog", "Giriş Ekranı"))
        self.lnekullaniciadi.setPlaceholderText(_translate("Dialog", "  Kullanıcı Adı"))
        self.label_2.setText(_translate("Dialog", "Henüz bir kaydın yok mu?"))
        self.lnesifre.setPlaceholderText(_translate("Dialog", "  Şifre"))
        self.btnytube.setText(_translate("Dialog", "M"))
        self.label_3.setText(_translate("Dialog", "YouTube kanalını ziyaret etmek için tıklayınız."))
