# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KayitEkrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KayitOl(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 611)
        Dialog.setStyleSheet("background-color: rgb(239, 231, 204);\n"
"")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(40, 40, 391, 531))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        self.lineEdit.setFont(font)
        self.lineEdit.setMouseTracking(True)
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setStyleSheet("background-color: rgb(193, 187, 168);\n"
"border-radius: 40px;")
        self.lineEdit.setObjectName("lineEdit")
        self.btnkayit = QtWidgets.QPushButton(Dialog)
        self.btnkayit.setGeometry(QtCore.QRect(110, 390, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnkayit.setFont(font)
        self.btnkayit.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(196, 199, 198);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    background-color: rgb(143, 145, 144);\n"
"}")
        self.btnkayit.setObjectName("btnkayit")
        self.rdsifregoster = QtWidgets.QRadioButton(Dialog)
        self.rdsifregoster.setGeometry(QtCore.QRect(110, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.rdsifregoster.setFont(font)
        self.rdsifregoster.setStyleSheet("background-color: rgb(193, 187, 168);\n"
"color: black;")
        self.rdsifregoster.setObjectName("rdsifregoster")
        self.btniptal = QtWidgets.QPushButton(Dialog)
        self.btniptal.setGeometry(QtCore.QRect(230, 390, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btniptal.setFont(font)
        self.btniptal.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(196, 199, 198);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    background-color: rgb(143, 145, 144);\n"
"}")
        self.btniptal.setObjectName("btniptal")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 70, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(193, 187, 168);\n"
"\n"
"")
        self.label.setObjectName("label")
        self.lnekullaniciadi1 = QtWidgets.QLineEdit(Dialog)
        self.lnekullaniciadi1.setGeometry(QtCore.QRect(100, 190, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.lnekullaniciadi1.setFont(font)
        self.lnekullaniciadi1.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(37, 39, 48);\n"
"    border-radius:20px;\n"
"    color: black;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    \n"
"    \n"
"    background-color: rgb(196, 199, 198);\n"
"    \n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    \n"
"    background-color: rgb(143, 145, 144);\n"
"}")
        self.lnekullaniciadi1.setObjectName("lnekullaniciadi1")
        self.lnesifre1 = QtWidgets.QLineEdit(Dialog)
        self.lnesifre1.setGeometry(QtCore.QRect(100, 240, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.lnesifre1.setFont(font)
        self.lnesifre1.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(37, 39, 48);\n"
"    border-radius:20px;\n"
"    color: black;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    \n"
"    \n"
"    background-color: rgb(196, 199, 198);\n"
"    \n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    \n"
"    background-color: rgb(143, 145, 144);\n"
"}")
        self.lnesifre1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnesifre1.setObjectName("lnesifre1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Kayıt Ol"))
        self.btnkayit.setText(_translate("Dialog", "Kayıt Ol"))
        self.rdsifregoster.setText(_translate("Dialog", "Şifreyi göster"))
        self.btniptal.setText(_translate("Dialog", "İptal Et"))
        self.label.setText(_translate("Dialog", "Kayıt Ekranı"))
        self.lnekullaniciadi1.setPlaceholderText(_translate("Dialog", "  Kullanıcı Adı"))
        self.lnesifre1.setPlaceholderText(_translate("Dialog", "  Şifre"))
