# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'liste.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_liste(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2052, 898)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tblw_HastaBilgi = QtWidgets.QTableWidget(self.centralwidget)
        self.tblw_HastaBilgi.setEnabled(True)
        self.tblw_HastaBilgi.setGeometry(QtCore.QRect(20, 60, 1881, 721))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        self.tblw_HastaBilgi.setFont(font)
        self.tblw_HastaBilgi.setStyleSheet("background-color: rgb(239, 231, 204);\n"
"color: rgb(0, 0, 0);\n"
"gridline-color: rgb(193, 187, 168);")
        self.tblw_HastaBilgi.setAlternatingRowColors(False)
        self.tblw_HastaBilgi.setIconSize(QtCore.QSize(0, 0))
        self.tblw_HastaBilgi.setRowCount(100)
        self.tblw_HastaBilgi.setColumnCount(53)
        self.tblw_HastaBilgi.setObjectName("tblw_HastaBilgi")
        self.btn_Kayit_Sil = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Kayit_Sil.setGeometry(QtCore.QRect(760, 790, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_Kayit_Sil.setFont(font)
        self.btn_Kayit_Sil.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.btn_Kayit_Sil.setObjectName("btn_Kayit_Sil")
        self.btn_Listele = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Listele.setGeometry(QtCore.QRect(890, 790, 93, 41))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(20)
        self.btn_Listele.setFont(font)
        self.btn_Listele.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.btn_Listele.setObjectName("btn_Listele")
        self.btn_Cikis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cikis.setGeometry(QtCore.QRect(1010, 790, 93, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(20)
        self.btn_Cikis.setFont(font)
        self.btn_Cikis.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.btn_Cikis.setObjectName("btn_Cikis")
        self.kayitsayisi1 = QtWidgets.QLabel(self.centralwidget)
        self.kayitsayisi1.setGeometry(QtCore.QRect(70, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kayitsayisi1.setFont(font)
        self.kayitsayisi1.setObjectName("kayitsayisi1")
        self.kayitsayisi = QtWidgets.QLabel(self.centralwidget)
        self.kayitsayisi.setGeometry(QtCore.QRect(170, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kayitsayisi.setFont(font)
        self.kayitsayisi.setText("")
        self.kayitsayisi.setObjectName("kayitsayisi")
        self.btn_geri = QtWidgets.QPushButton(self.centralwidget)
        self.btn_geri.setGeometry(QtCore.QRect(50, 790, 93, 41))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(36)
        self.btn_geri.setFont(font)
        self.btn_geri.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(239, 231, 204);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    background-color: rgb(251, 197, 123);\n"
"}")
        self.btn_geri.setObjectName("btn_geri")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1921, 831))
        self.label.setStyleSheet("background-color: rgb(193, 187, 168);\n"
"border-radius: 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.tblw_HastaBilgi.raise_()
        self.btn_Kayit_Sil.raise_()
        self.btn_Listele.raise_()
        self.btn_Cikis.raise_()
        self.kayitsayisi1.raise_()
        self.kayitsayisi.raise_()
        self.btn_geri.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2052, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Kayit_Sil.setText(_translate("MainWindow", ""))
        self.btn_Listele.setText(_translate("MainWindow", "3"))
        self.btn_Cikis.setText(_translate("MainWindow", ""))
        self.kayitsayisi1.setText(_translate("MainWindow", "Kayıt Sayısı:"))
        self.btn_geri.setText(_translate("MainWindow", ""))
